### PR TITLE
Add Blog about Eclipse Jkube(https://www.eclipse.org/jkube/) on Red Hat Developers to planet

### PR DESCRIPTION
**Pull request by rohanKanojia**
This blog demonstrates Eclipse Jkube's Kubernetes Maven Plugin for deploying a maven application to Kubernetes.

### CODE REVIEW

**Comment by chrisguindon** [comment]
Dear @rohanKanojia,

Thank you for contribution, unfortunaly we can accept as-is since https://developers.redhat.com/blog/2020/01/28/introduction-to-eclipse-jkube-java-tooling-for-kubernetes-and-red-hat-openshift/ is not an rss feed. We can't add individual blog post to planeteclipse.org:

> The issue or pull request must include a picture (185x185), the RSS feed url for the blog and the full name of the author.

We will be happy to include you in our list of authors if you can provide an RSS feed with posts that follows our Guidelines: https://github.com/EclipseFdn/planeteclipse.org#guidelines

**Review by chrisguindon — CHANGES_REQUESTED** [review]
Please provide an RSS feed url for the blog. All post from the RSS Feed must be relevant to the Eclipse community!

Thanks

**Comment by rohanKanojia** [comment]
@chrisguindon: You mean replace blog url with this: https://developers.redhat.com/blog/2020/01/28/introduction-to-eclipse-jkube-java-tooling-for-kubernetes-and-red-hat-openshift/feed/ or https://developers.redhat.com/blog/author/rokumar/feed/ ?

**Comment by chrisguindon** [comment]
> @chrisguindon: You mean replace blog url with this: https://developers.redhat.com/blog/2020/01/28/introduction-to-eclipse-jkube-java-tooling-for-kubernetes-and-red-hat-openshift/feed/ or https://developers.redhat.com/blog/author/rokumar/feed/ ?

No, this seems to be a feed for your comments!

**Comment by chrisguindon** [comment]
This is perfect @rohanKanojia 

Thanks!

**Pull request merged**
