### PR TITLE
Add Wim and Sharon as bloggers

### PR DESCRIPTION
**Pull request by chrisguindon**

### CODE REVIEW

**Comment by chrisguindon** [comment]
@guw and @jmini 

We don't really have a formal review process! I added both of you for review but please let me know if I should also include other folks!

**Review by jmini — APPROVED** [review]
+1

There was never a formal process to approve members on Planet.

**Comment by guw** [comment]
@chrisguindon see https://github.com/EclipseFdn/planeteclipse.org#guidelines :)

**Comment by chrisguindon** [comment]
I was referring to PR in general, not only adding authors which was the case here!

thanks

**Pull request merged**
